// Run: node tests/demo-flow.cjs <path-to-playwright-package>
const assert = require('node:assert/strict');
const { chromium } = require(process.argv[2] || 'playwright');
const base = process.env.TEST_BASE_URL || 'http://localhost:4321';
const uuid = /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i;
(async () => {
 const browser = await chromium.launch({ channel: 'msedge', headless: true });
 const context = await browser.newContext();
 const page = await context.newPage();
 const errors = [];
 page.on('pageerror', error => errors.push(error.message));
 const doc = `DEMO${Date.now()}`;
 async function visibleSafe() { assert(!uuid.test(await page.locator('body').innerText()), 'Visible UUID'); assert(!uuid.test(page.url()), 'UUID in URL'); }
 async function identify(mode, document = doc, email = 'demo@example.test') {
  await page.locator('[name=mode]').selectOption(mode);
  await page.locator('[name=document_number]').fill(document);
  await page.locator('[name=email]').fill(email);
  if (mode === 'register') await page.locator('[name=full_name]').fill('Pasajera Demo');
  await visibleSafe();
  await page.locator('#profile-form button').click();
 }
 try {
  assert.equal((await context.request.get(`${base}/api/bookings`)).status(), 401);
  await page.goto(base);
  await page.waitForFunction(() => document.querySelectorAll('.flight-card').length === 9);
  await visibleSafe();
  const flights = await (await context.request.get(`${base}/api/flights`)).json();
  assert.equal(flights.length, 9); assert(!uuid.test(JSON.stringify(flights)));
  assert(flights.every(f => f.available_seats >= 0 && f.available_seats <= f.total_capacity && new Date(f.departure_at) > new Date()));
  const before = flights.find(f => f.flight_number === 'AR404').available_seats;
  await page.locator('#origin-filter').selectOption('Cali');
  await page.locator('#destination-filter').selectOption('Bogotá');
  assert.equal(await page.locator('.flight-card').count(), 1);
  await page.getByRole('button', { name: 'Seleccionar' }).click();
  await page.waitForURL('**/ingresar?**');
  assert(page.url().includes('AR404'));
  await identify('register');
  await page.waitForURL('**/reservar?vuelo=AR404');
  await page.locator('#reservation-form').waitFor({ state: 'visible' });
  assert.equal(await page.locator('input').count(), 0);
  await visibleSafe();
  await page.getByRole('button', { name: 'Confirmar reserva' }).click();
  await page.locator('#confirmation').waitFor({ state: 'visible' });
  const code = await page.locator('#booking-code').innerText();
  assert.match(code, /^RES-/); await visibleSafe();
  const after = await (await context.request.get(`${base}/api/flights`)).json();
  assert.equal(after.find(f => f.flight_number === 'AR404').available_seats, before - 1);
  await page.getByRole('link', { name: 'Ver Mis reservas y cancelar' }).click();
  await page.getByRole('heading', { name: code }).waitFor();
  assert.match(await page.locator('#bookings').innerText(), /AR404.*Cali.*Bogotá/);
  await visibleSafe();
  const bookings = await (await context.request.get(`${base}/api/bookings?id=anything`)).json();
  assert.equal(bookings.length, 1); assert(!uuid.test(JSON.stringify(bookings)));
  console.log('PASS catálogo (9), filtros, selección anónima, registro, retorno, creación y Mis reservas; cupo -1; sin UUID');
  const cookie = (await context.cookies()).find(c => c.name === 'aeroreserva_session');
  assert(cookie.httpOnly); assert.equal(cookie.sameSite, 'Lax');
  const other = await browser.newContext();
  const response = await other.request.post(`${base}/api/passengers`, { headers: { Origin: base }, data: { mode: 'register', document_type: 'CC', document_number: doc + 'B', full_name: 'Otro Pasajero', email: 'otro@example.test' } });
  assert.equal(response.status(), 201);
  assert.deepEqual(await (await other.request.get(`${base}/api/bookings`)).json(), []);
  assert.equal((await other.request.delete(`${base}/api/bookings`, { headers: { Origin: base }, data: { booking_code: code } })).status(), 404);
  assert.equal((await other.request.post(`${base}/api/bookings`, { headers: { Origin: 'https://other.invalid' }, data: { flight_number: 'AR404' } })).status(), 403);
  await other.addCookies([{ ...cookie, value: cookie.value + 'tampered' }]);
  assert.equal((await other.request.get(`${base}/api/bookings`)).status(), 401);
  await other.close();
  console.log('PASS aislamiento entre pasajeros, cancelación ajena rechazada, origen externo rechazado y cookie alterada rechazada');
  await page.getByRole('button', { name: 'Salir', exact: true }).click();
  await page.waitForURL(base + '/');
  assert.equal((await context.request.get(`${base}/api/bookings`)).status(), 401);
  await page.getByRole('link', { name: 'Ingresar', exact: true }).click();
  await identify('login', doc, 'incorrecto@example.test');
  await page.locator('#profile-message').waitFor({ state: 'visible' });
  assert.match(await page.locator('#profile-message').innerText(), /No encontramos/);
  await identify('login');
  await page.waitForURL('**/reservas');
  await page.getByRole('heading', { name: code }).waitFor();
  await page.reload();
  await page.getByRole('heading', { name: code }).waitFor();
  await page.getByRole('button', { name: 'Cancelar reserva', exact: true }).click();
  await page.getByText('Reserva cancelada correctamente.').waitFor();
  assert.equal(await page.locator('.status').innerText(), 'Cancelada');
  await page.reload();
  await page.getByText('Cancelada', { exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Cancelar reserva', exact: true }).count(), 0);
  const final = await (await context.request.get(`${base}/api/flights`)).json();
  assert.equal(final.find(f => f.flight_number === 'AR404').available_seats, before);
  assert.equal((await context.request.delete(`${base}/api/bookings`, { headers: { Origin: base }, data: { booking_code: code } })).status(), 409);
  await visibleSafe();
  await page.setViewportSize({ width: 390, height: 844 });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.goto(base);
  await page.locator('[data-flight-number=AR404]').click();
  await page.waitForURL('**/reservar?vuelo=AR404');
  await page.locator('#reservation-form').waitFor({ state: 'visible' });
  assert.equal(await page.locator('input').count(), 0);
  await page.getByRole('button', { name: 'Confirmar reserva' }).click();
  await page.locator('#confirmation').waitFor({ state: 'visible' });
  const secondCode = await page.locator('#booking-code').innerText();
  assert.notEqual(secondCode, code);
  await page.getByRole('link', { name: 'Ver Mis reservas y cancelar' }).click();
  await page.getByRole('heading', { name: secondCode }).waitFor();
  await page.getByRole('button', { name: 'Cancelar reserva', exact: true }).click();
  await page.getByText('Reserva cancelada correctamente.').waitFor();
  await visibleSafe();
  console.log('PASS selección y nueva reserva con pasajero ya identificado, sin pedir datos; segunda reserva cancelada');
  assert.deepEqual(errors, []);
  console.log('PASS salir, correo incorrecto, reingreso, persistencia al recargar, cancelación persistida y cupo restaurado; cancelación repetida 409; móvil sin desbordamiento; sin errores JS');
  console.log(`Datos de prueba conservados: ${doc}, ${doc}B; reserva ${code} cancelada.`);
 } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
