# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: aeroreserva.proto for package 'aeroreserva.v1'

require 'grpc'
require 'aeroreserva_pb'

module Aeroreserva
  module V1
    module FlightService
      # ==================== VUELOS ====================
      #
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'aeroreserva.v1.FlightService'

        rpc :ListFlights, ::Aeroreserva::V1::Empty, ::Aeroreserva::V1::FlightList
        rpc :GetFlight, ::Aeroreserva::V1::GetByIdRequest, ::Aeroreserva::V1::Flight
        rpc :CheckAvailability, ::Aeroreserva::V1::GetByIdRequest, ::Aeroreserva::V1::AvailabilityResponse
        rpc :OccupySeat, ::Aeroreserva::V1::GetByIdRequest, ::Aeroreserva::V1::Flight
        rpc :ReleaseSeat, ::Aeroreserva::V1::GetByIdRequest, ::Aeroreserva::V1::Flight
      end

      Stub = Service.rpc_stub_class
    end
    module PassengerService
      # ==================== PASAJEROS ====================
      #
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'aeroreserva.v1.PassengerService'

        rpc :CreatePassenger, ::Aeroreserva::V1::CreatePassengerRequest, ::Aeroreserva::V1::Passenger
        rpc :GetPassenger, ::Aeroreserva::V1::GetByIdRequest, ::Aeroreserva::V1::Passenger
      end

      Stub = Service.rpc_stub_class
    end
    module BookingService
      # ==================== RESERVAS ====================
      #
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'aeroreserva.v1.BookingService'

        rpc :CreateBooking, ::Aeroreserva::V1::CreateBookingRequest, ::Aeroreserva::V1::Booking
        rpc :GetBooking, ::Aeroreserva::V1::GetByIdRequest, ::Aeroreserva::V1::Booking
        rpc :ListBookings, ::Aeroreserva::V1::Empty, ::Aeroreserva::V1::BookingList
        rpc :CancelBooking, ::Aeroreserva::V1::GetByIdRequest, ::Aeroreserva::V1::Booking
      end

      Stub = Service.rpc_stub_class
    end
  end
end
